---
title: "Santiago 2021 Table 1"
author: "John Santiago"
output:
  html_document:
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE, warning=FALSE}
library(goseq)
library(KEGGREST)
##ID conversion table
convert=read.csv("https://raw.githubusercontent.com/DavidRandLab/Santiago-et-al-2021-BMC-Genomics/main/Data%20Files/FBgnConversionTable.csv",row.names=1)

oocsoc=read.csv("https://raw.githubusercontent.com/DavidRandLab/Santiago-et-al-2021-BMC-Genomics/main/Data%20Files/ImpulseDE%20Outputs/Table%20S3G%20OOC-SOC.csv",row.names=1)
oorsor=read.csv("https://raw.githubusercontent.com/DavidRandLab/Santiago-et-al-2021-BMC-Genomics/main/Data%20Files/ImpulseDE%20Outputs/Table%20S3H%20OOR-SOR.csv",row.names=1)
cpm=read.csv("https://raw.githubusercontent.com/DavidRandLab/Santiago-et-al-2021-BMC-Genomics/main/Data%20Files/Trimmed.CPM.data.csv",row.names=1)

##ImpulseDE2 output tables with significant genes only
OCSC=na.omit(oocsoc[oocsoc$padj<.05,])
ORSR=na.omit(oorsor[oorsor$padj<.05,])

kegg=keggLink("pathway","dme")

##i=1
##kegg.names=unique(substr(kegg,6,13))
##names(kegg.names)=as.vector(kegg.names)
##while(i<=length(kegg.names)){
  ##kegg.names[i] <- strsplit(keggGet(kegg.names[i])[[1]]$NAME," - ")[[1]][1]
  ##i=i+1
##}
kegg.names=read.csv("https://raw.githubusercontent.com/DavidRandLab/Santiago-et-al-2021-BMC-Genomics/main/Data%20Files/kegg.names.csv",row.names=1)

temp=names(kegg)
temp2=convert[convert[,5]!="",]
i=1
while(i<=nrow(temp2)){
  if(length(temp[temp==temp2[i,5]])){
    temp[temp==temp2[i,5]]=as.character(temp2[i,4])
  }
  i=i+1
}

names(kegg)=temp
kegg=as.list(kegg)

```


```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.show = 'hide'}
##KEGG enrichment for OreR;OreR Rapa vs sm21;OreR Rapa
DEGs=setdiff(row.names(ORSR),row.names(convert)[convert$mt==1])
temp=row.names(cpm)
temp=setdiff(temp,row.names(convert)[convert$mt==1])
genes=c(rep(0,length(temp)))
names(genes)=temp
genes[DEGs]=1
names(genes)=convert[names(genes),"Symbol"]
genes=genes[na.omit(unique(names(genes)))]

pwf=nullp(genes,"dm3","geneSymbol")

## For GO term enrichment table
## Not used for table 1
##GO term enrichment is GO.wall
##ORSR.GO.Table=goseq(pwf,"dm3","geneSymbol")

##KEGG term enrichment is KEGG
KEGG=goseq(pwf,gene2cat=kegg)
KEGG$adjp=p.adjust(KEGG$over_represented_pvalue,method="BH")
row.names(KEGG)=substr(as.character(KEGG[,1]),6,13)
KEGG$Name=kegg.names[row.names(KEGG),"KEGG.name"]
##Remove Global and Overview Maps
KEGG=KEGG[substr(row.names(KEGG),1,6)!="dme011",]
ORSR.KEGG.Table=KEGG[substr(row.names(KEGG),1,6)!="dme012",]
sigORSR.KEGG.Table=ORSR.KEGG.Table[ORSR.KEGG.Table[,"adjp"]<.05,]
```


```{r, echo = FALSE, message=FALSE, warning=FALSE, fig.show = 'hide'}
#### OreR;OreR Control vs sm21;OreR Control
DEGs=setdiff(row.names(OCSC),row.names(convert)[convert$mt==1])
temp=row.names(cpm)
temp=setdiff(temp,row.names(convert)[convert$mt==1])
genes=c(rep(0,length(temp)))
names(genes)=temp
genes[DEGs]=1
names(genes)=convert[names(genes),"Symbol"]
genes=genes[na.omit(unique(names(genes)))]

pwf=nullp(genes,"dm3","geneSymbol")

## Not used for table 1
##GO term enrichment is GO.wall
##OCSC.GO.Table=goseq(pwf,"dm3","geneSymbol")

##KEGG term enrichment is KEGG
KEGG=goseq(pwf,gene2cat=kegg)
KEGG$adjp=p.adjust(KEGG$over_represented_pvalue,method="BH")
row.names(KEGG)=substr(as.character(KEGG[,1]),6,13)
KEGG$Name=kegg.names[row.names(KEGG),"KEGG.name"]
##Remove Global and Overview Maps
KEGG=KEGG[substr(row.names(KEGG),1,6)!="dme011",]
OCSC.KEGG.Table=KEGG[substr(row.names(KEGG),1,6)!="dme012",]
sigOCSC.KEGG.Table=OCSC.KEGG.Table[OCSC.KEGG.Table[,"adjp"]<.05,]
```

<br  /><br  /><br  />
***Table 1***<br  />
KEGG enrichment analysis for OreR;OreR vs sm21;OreR with or without rapamycin
```{r}
combined.table=data.frame("ORSR DE in Cat."= sigORSR.KEGG.Table[,"numDEInCat"], 
                          "ORSR All in Cat."= sigORSR.KEGG.Table[,"numInCat"], 
                          "ORSR adj p-value" = sigORSR.KEGG.Table[,"adjp"], 
                          "OCSC DE in Cat."= OCSC.KEGG.Table[row.names(sigORSR.KEGG.Table),"numDEInCat"], 
                          "OCSC All in Cat."= OCSC.KEGG.Table[row.names(sigORSR.KEGG.Table),"numInCat"], 
                          "OCSC adj p-value" = OCSC.KEGG.Table[row.names(sigORSR.KEGG.Table),"adjp"])
row.names(combined.table)=kegg.names[row.names(sigORSR.KEGG.Table),"KEGG.Name"]
combined.table
```